{
 "title": "AP Sensor Data",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "import \"join\"\n\nleft = from(bucket: \"sensordata\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XE-wireless-access-point-oper:access-point-oper-data/ap-temp\")\n  |> filter(fn: (r) => r[\"_field\"] == \"temp\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> group()\n  //|> yield(name: \"temperature_table\")\n\nright = from(bucket: \"sensordata\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XE-wireless-access-point-oper:access-point-oper-data/ap-name-mac-map\")\n  |> filter(fn: (r) => r[\"_field\"] == \"wtp_mac\")\n  |> unique()\n  |> group()\n  //|> yield(name: \"ap_name_mac_table\")\n\nall = join.inner(\n  left: left,\n  right: right,\n  on: (l, r) => l.ap_mac == r._value,\n  as: (l, r) => ({l with _value: l._value, ap_name: r.wtp_name}),\n)\n  |> group(columns: [\"_value\", \"_time\"], mode: \"except\")\n  |> yield(name: \"data\")\n"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "import \"join\"\n\nleft = from(bucket: \"sensordata\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XE-wireless-access-point-oper:access-point-oper-data/ap-temp\" or r[\"_measurement\"] == \"Cisco-IOS-XE-wireless-access-point-oper:access-point-oper-data/ap-air-quality\")\n  |> filter(fn: (r) => r[\"_field\"] == \"humidity\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> group()\n  //|> yield(name: \"humidity_table\")\n\nright = from(bucket: \"sensordata\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XE-wireless-access-point-oper:access-point-oper-data/ap-name-mac-map\")\n  |> filter(fn: (r) => r[\"_field\"] == \"wtp_mac\")\n  |> unique()\n  |> group()\n  //|> yield(name: \"ap_name_mac_table\")\n\nall = join.inner(\n  left: left,\n  right: right,\n  on: (l, r) => l.ap_mac == r._value,\n  as: (l, r) => ({l with _value: l._value, ap_name: r.wtp_name}),\n)\n  |> group(columns: [\"_value\", \"_time\"], mode: \"except\")\n  |> yield(name: \"data\")\n"
    }
   ]
  },
  {
   "title": "TVOC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "import \"join\"\n\nleft = from(bucket: \"sensordata\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XE-wireless-access-point-oper:access-point-oper-data/ap-temp\" or r[\"_measurement\"] == \"Cisco-IOS-XE-wireless-access-point-oper:access-point-oper-data/ap-air-quality\")\n  |> filter(fn: (r) => r[\"_field\"] == \"tvoc\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> group()\n  //|> yield(name: \"tvoc_table\")\n\nright = from(bucket: \"sensordata\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XE-wireless-access-point-oper:access-point-oper-data/ap-name-mac-map\")\n  |> filter(fn: (r) => r[\"_field\"] == \"wtp_mac\")\n  |> unique()\n  |> group()\n  //|> yield(name: \"ap_name_mac_table\")\n\nall = join.inner(\n  left: left,\n  right: right,\n  on: (l, r) => l.ap_mac == r._value,\n  as: (l, r) => ({l with _value: l._value, ap_name: r.wtp_name}),\n)\n  |> group(columns: [\"_value\", \"_time\"], mode: \"except\")\n  |> yield(name: \"data\")\n"
    }
   ]
  }
 ]
}